name: get_connect_logger
description: "Console logger for GetConnect"
version: 1.0.1
repository: "https://github.com/BenjaminMahmic/get_connect_logger"
platforms:
  android:
  ios:
  macos:
  windows:
  linux:
  web:

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
